analytics: {}
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.44670904078520834
  lightness: 0.25
  rhythmicContrast: 0.25
  saturation: 0.3125
cta: {}
layout_spectrum: 0.967342
name: smallandwicked
opengraph: {}
purpose: []
typography_spectrum: 0.05518
